#!/bin/sh

LINKPARSES="/tmp/LinksToDAG_linkparses.txt"
rm -f $LINKPARSES
touch $LINKPARSES

if [ $2 ]; then
    COUNTER=1
fi

while read line; do
    #echo $line 1>&2
    #echo $line | link-parser -\!echo=0 2> /dev/null
    echo $line | link-parser -\!graphics=0 -\!links=0 -\!echo=1 -\!postscript=1 2> /dev/null >> $LINKPARSES


    if [ $? != 0 ]; then
        exit
    fi


    if [ $2 ]; then
        if [ $COUNTER -ge $2 ]; then
            break
        else
            COUNTER=$((COUNTER+1))
        fi
    fi

done < $1




python src/main.py $LINKPARSES



if [ $2 ]; then
    echo "finished" $2 "sentences"
    echo
fi
