#!/bin/sh

LINKPARSES="/tmp/LinksToDAG_linkparses.txt"
rm -f $LINKPARSES
touch $LINKPARSES

if [ $2 ]; then
    COUNTER=1
fi

python src/link_parser.py $1 $2 $3



if [ $2 ]; then
    python src/main.py $LINKPARSES -id $1$2
else    
    python src/main.py $LINKPARSES -id $1
fi


#python src/linkEdgeSolver.py $LINKPARSES




if [ $2 ]; then
    echo
    echo "FINISHED" $2 "SENTENCES"
    echo
    echo
fi



#echo "sol/links.conll" | mutt -s 

#wc -l $1 | mutt -s "sol/links.conll" -a sol/links.conll -a sol/allowedLinks.txt -- junekihong@gmail.com

